title: "「タワーディフェンス」設計の振り返り"
summary: "個人開発のUnityゲーム「タワーディフェンス」の設計についての振り返りです。"
topics: ["unity", "アーキテクチャ", "個人開発"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 0-intro
  - z-changelog
