title: "自作ゲームの設計パターン試行錯誤"
summary: "自作ゲーム開発をする中で学んだことや実践したことのまとめです。実装よりも設計の話を多くしたいです。"
topics: ["unity"] # トピック（5つまで）
published: false
price: 0
toc_depth: 2
chapters:
  - intro
  - what-write
  - 1-3d_maze
  - 2-hakoirimusume
  - 3-seiza-1
  - 3-seiza-2
  - 3-seiza-3
