title: "「ことばパズル」設計の振り返り"
summary: "個人開発のUnityゲーム「ことばパズル」の設計についての振り返りです。"
topics: ["unity", "アーキテクチャ", "個人開発"]
published: false
price: 0
toc_depth: 3
chapters:
  - 0-intro
  - architecture
  - architecture-core
  - architecture-domain
  - architecture-application
  - architecture-presentation
  - architecture-infrastructure
  - folder-github
  - folder-unity
  - folder-csharp
  - application-session
  - presentation-components-coop
  - presentation-ui
  - settings
  - y-gitignore
  - y-tag
  - z-changelog
